---
title: "1212"
output: html_notebook
---

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
library(stringr)
library(dplyr)
libraryData$書籍館藏地 %>% as.factor %>% levels -> storageLocations
storageLocations
```

```{r}
i<-2
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i}
```

```{r}
libraryData$學院%>%as.factor%>%levels->college
#0
collegeBorrowCount<-vector("numeric",length(college))
for(i in c(1:length(college))){
  #1
  college_i<-college[i]
  #2
  numericalIndexForSample<-which(libraryData$學院==college_i)
  collegesubsample_i<-libraryData[numericalIndexForSample,]
  #3
  collegeBorrowCount_i<-nrow(collegesubsample_i)
  #4
  collegeBorrowCount[[i]]<-collegeBorrowCount_i}
  

```

```{r}
libraryData$學號%>%as.factor%>%levels->student
#0
studentBorrow<-vector("numeric",length(student))
for(i in c(1:length(student))){
  #1
  student_i<-student[i]
  #2
  numericalIndex<-which(libraryData$學號==student_i)
  studentsubsample_i<-libraryData[numericalIndex,]
  #3
  studentBorrow_i<-nrow( studentsubsample_i)
  #4
  studentBorrow[[i]]<-studentBorrow_i}
  
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  )%>%
  ungroup-> result2
result2
```

```{r}
libraryData%>%
  filter(入學年==102)
```
##first time to library
```{r}
library(lubridate)
libraryData%>%
  mutate(借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei"))%>%
  group_by(學號)%>%
  summarise(第一次借書=min(借閱時間))%>%
  ungroup->result3
result3
```

