---
title: '2018-10-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
```


```{r}
names(StuDF) <- c("學號","姓名","成績")
names(StuDF)
```

```{r}
names(StuDF)[2]<-c("姓名")
names(StuDF)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```


```{r}
student$新身高級距 <- student$身高級距
levels(student$新身高級距)[c(1:3)]<-c("(0,160]")
```


```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
class(classSurvey)
```

```{r}
classSurvey$學號<-as.character(classSurvey$學號)
library(stringr)
classSurvey$年級<-str_sub(classSurvey$學號,2,4)
classSurvey$年級<-as.factor(classSurvey$年級)
levels(classSurvey$年級)<-c("大四及以上","大三", "大二","大一")
```

```{r}
classSurvey$年級
```

```{r}
freshIndicater<-(classSurvey$年級=="大一")
freshActivity<-classSurvey$本學期目前已參加之課外活動[freshIndicater]
library(stringr)
str_split_fixed(freshActivity,",",n=5)->aa
str_c(aa)->bb
table(bb)
```


