---
title: "R Notebook"
output: html_notebook
---

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1L,3L,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer["greenBox"] # or plasticContainer[c(1,2)]
plasticContainer["greenBox"]$greenBox[1]
plasticContainer["greenBox"][["greenBox"]][1]
```

```{r}
plasticContainer[["greenBox"]] [1]# or plasticContainer[[1]]

```

```{r}
plasticContainer$greenBox[1]
plasticContainer$greenBox[[1]]
```

```{r}
download.file("https://github.com/tpemartin/github-data/blob/master/plotly_4070_neda.Rda?raw=true",destfile = "plotly_4070_neda.Rda")
load("plotly_4070_neda.Rda")
library(plotly)
plotly_4070_neda
```

```{r}
plotly_4070_neda$x$layout$shapes[[1]]$opacity<-0.8
plotly_4070_neda
```

```{r}
library(readr)
transcriptData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcript100_102.csv",
                  col_types = cols(
                    學期成績="n"
                  ))

totalCredits<-function(x){
  transcriptData[transcriptData$學號==x,]->subsample 
  subsample %>%
    mutate(
      及格=(學期成績>=60)
    ) %>%
    summarise(
      學號=學號[1],
      總修習學分數=sum(學分數),
      總實得學分數=sum(學分數[及格])
    )  
}
```

```{r}
library(readr)
library(tidyr)

library(dplyr)
libraryData %>%
  group_by(學院) %>%
  nest(.key="各院借閱資料") ->
  libraryDataNested
libraryDataNested
```

